# Lista ampliada de controles basada en ISO 27001 en español
controls = [
    {"id": "A.5.1", "description": "Directrices de gestión para la seguridad de la información", "completed": False},
    {"id": "A.6.1", "description": "Organización interna", "completed": False},
    {"id": "A.6.2", "description": "Dispositivos móviles y teletrabajo", "completed": False},
    {"id": "A.7.1", "description": "Antes del empleo", "completed": False},
    {"id": "A.7.2", "description": "Durante el empleo", "completed": False},
    {"id": "A.7.3", "description": "Terminación o cambio de empleo", "completed": False},
    {"id": "A.8.1", "description": "Responsabilidad por los activos", "completed": False},
    {"id": "A.8.2", "description": "Clasificación de la información", "completed": False},
    {"id": "A.8.3", "description": "Manejo de medios", "completed": False},
    {"id": "A.9.1", "description": "Requisitos de negocio para el control de acceso", "completed": False},
    {"id": "A.9.2", "description": "Gestión de acceso de usuarios", "completed": False},
    {"id": "A.9.3", "description": "Responsabilidades de los usuarios", "completed": False},
    {"id": "A.9.4", "description": "Control de acceso al sistema y a las aplicaciones", "completed": False},
    {"id": "A.10.1", "description": "Controles criptográficos", "completed": False},
    {"id": "A.11.1", "description": "Áreas seguras", "completed": False},
    {"id": "A.11.2", "description": "Seguridad de los equipos", "completed": False},
    {"id": "A.12.1", "description": "Procedimientos y responsabilidades operativas", "completed": False},
    {"id": "A.12.2", "description": "Protección contra malware", "completed": False},
    {"id": "A.12.3", "description": "Copia de seguridad", "completed": False},
    {"id": "A.12.4", "description": "Registro y monitoreo", "completed": False},
    {"id": "A.12.5", "description": "Control del software operativo", "completed": False},
    {"id": "A.13.1", "description": "Gestión de la seguridad de la red", "completed": False},
    {"id": "A.13.2", "description": "Seguridad en la transferencia de información", "completed": False},
    {"id": "A.14.1", "description": "Requisitos de seguridad de los sistemas de información", "completed": False},
    {"id": "A.14.2", "description": "Seguridad en los servicios de desarrollo y soporte", "completed": False},
    {"id": "A.15.1", "description": "Seguridad en las relaciones con los proveedores", "completed": False},
    {"id": "A.15.2", "description": "Gestión de la entrega del servicio por el proveedor", "completed": False},
    {"id": "A.16.1", "description": "Gestión de incidentes de seguridad de la información", "completed": False},
    {"id": "A.17.1", "description": "Continuidad de la seguridad de la información", "completed": False},
    {"id": "A.18.1", "description": "Cumplimiento con los requisitos legales y contractuales", "completed": False},
    {"id": "A.18.2", "description": "Revisión de la seguridad de la información", "completed": False},
]
